version: '2.1'

services:

  # The Drone Delivery service, a J2E system
  dd_system:
    image: team-d/dd-internal
    container_name: dd_system
    environment:
      - bank_host=dd_partners
      - bank_port=9090
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - external_partners

  # The external partners, implemented as .Net services
  external_partners:
    image: team-d/dd-external
    container_name: dd_partners
    expose:
        - "9090"
    ports:
      - "9090:9090"

  # CLIs
  client-customer-service:
    image: team-d/dd-client-customer-service
    container_name: dd_client-customer-service
    command: "dd_system 8080"
    volumes:
      - .:/host
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true
