version: '2.1'

services:

  # The Drone Delivery service, a J2E system
  dd_system:
    image: djotiham/dd-internal
    container_name: dd_system
    environment:
      - bank_host=dd_partners
      - bank_port=9090
    expose:
      - "80"
    ports:
      - "80:8080"
    depends_on:
      - external_partners

  # The external partners, implemented as .Net services
  external_partners:
    image: djotiham/dd-external
    container_name: dd_partners
    expose:
        - "9090"
    ports:
      - "9090:9090"

  # CLIs
  #customer service
  client-customer-service:
    image: djotiham/dd-client-customer-service
    container_name: dd_client-customer-service
    command: "dd_system 8080"
    volumes:
      - .:/host-customer-service
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true
  #clissandre
  client-clissandre:
    image: djotiham/dd-client-clissandre
    container_name: dd_client-clissandre
    command: "dd_system 8080"
    volumes:
      - .:/host-clissandre
    depends_on:
      dd_system:
        condition: service_healthy
    stdin_open: true
    tty: true
